# Generated by Django 5.1.4 on 2025-01-08 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuctionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "file",
                    models.FileField(
                        upload_to="auction_documents/", verbose_name="File"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Auction Document",
                "verbose_name_plural": "Auction Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Executor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Phone"),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Jurisdiction"
                    ),
                ),
            ],
            options={
                "verbose_name": "Executor",
                "verbose_name_plural": "Executors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "file",
                    models.ImageField(upload_to="auction_images/", verbose_name="File"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt text"
                    ),
                ),
                ("caption", models.TextField(blank=True, verbose_name="Caption")),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "municipality",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Municipality"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "cadastral_municipality",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Cadastral Municipality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["city", "municipality"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Code",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMATION_IN_PROGRESS", "Потврђивање у току"),
                            ("ACTIVE", "Потврђено"),
                        ],
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "publication_date",
                    models.DateTimeField(verbose_name="Publication Date"),
                ),
                ("start_time", models.DateTimeField(verbose_name="Start Time")),
                ("end_time", models.DateTimeField(verbose_name="End Time")),
                (
                    "starting_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Starting Price"
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Estimated Value"
                    ),
                ),
                (
                    "bidding_step",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Bidding Step"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "sale_number",
                    models.CharField(max_length=50, verbose_name="Sale Number"),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="auctions",
                        to="auctions.auctiondocument",
                        verbose_name="Documents",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auctions",
                        to="auctions.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auctions",
                        to="auctions.executor",
                        verbose_name="Executor",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="auctions",
                        to="auctions.image",
                        verbose_name="Images",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auctions",
                        to="auctions.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="auctions",
                        to="auctions.tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auction",
                "verbose_name_plural": "Auctions",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="auctions_au_status_c6232d_idx"
                    ),
                    models.Index(
                        fields=["start_time"], name="auctions_au_start_t_4a64bc_idx"
                    ),
                    models.Index(
                        fields=["publication_date"],
                        name="auctions_au_publica_e60c7d_idx",
                    ),
                ],
            },
        ),
    ]
